version: '3.9'
services:
  mysql:
    platform: linux/arm64
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: hIIImGary1782
      MYSQL_DATABASE: cartrackr_db
    volumes:
      - cartrackr_db:/var/lib/mysql
    ports:
      - '3306:3306'
  mailhog:
    image: 'mailhog/mailhog'
    container_name: 'mailhog'
    ports:
      - 8025:8025
      - 1025:1025
  adminer:
    platform: linux/x86_64
    image: adminer
    ports:
      - '8081:8080'
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: asdASD123
    command: server --console-address ":9001" /data
volumes:
  cartrackr_db:
    driver: local
  minio_storage: {}
